FROM opnfv/functest-kubernetes-cnf:v1.18

COPY testcases.yaml /usr/lib/python3.8/site-packages/xtesting/ci/testcases.yaml
COPY example-cnfs/envoy/cnf-testsuite.yml /src/cnf-testsuite/cnf-testsuite.yml
